### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by shrivastava95** [shrivastava95/docparser#2]
Make a Docker container for the repo which makes it easy to setup without installing all the requirements. Publish image on Docker Hub.

**Comment by rexdivakar** [comment]
Hey @shrivastava95 i would love to work on building the docker image for this issue, kindly assign it to me.

**Comment by shrivastava95** [comment]
Hey @rexdivakar thank you for your interest in this library. It would be great if we can have a chat over this on discord. My discord username is - ishaanshri95

**Comment by UncleWeeds** [comment]
If possible I would like to help on it too

**Comment by rexdivakar** [comment]
> Hey @rexdivakar thank you for your interest in this library. It would be great if we can have a chat over this on discord. My discord username is - ishaanshri95

I'm not able to find your id

**Comment by shrivastava95** [comment]
hey @rexdivakar @UncleWeeds please let me know your discord IDs or some way to get in contact with you over this.

**Comment by UncleWeeds** [comment]
I just need to know how to set it up locally (Linux)

**Comment by rexdivakar** [comment]
> shaanshri95

tried sending a friend request and my discord id is root5998

**Comment by shrivastava95** [comment]
Closed with https://github.com/shrivastava95/docparser/pull/5.
